### ISSUE TITLE
43_CNN bug in fncs: train_epoch

### ISSUE THREAD

**Issue by GeneralFire** [KaiL4eK/ml_edu#10]
Ошибка представлена на рис. ниже:
![image](https://user-images.githubusercontent.com/38854804/140198616-f467a0cc-cff6-4b02-b113-b509d7eba1c6.png)

вызвана неверным типом аргумента при вызове функции потерь.
Исправляется так, как представлено ниже:
![image](https://user-images.githubusercontent.com/38854804/140198731-80a5ee0e-e815-4c6a-bb16-bb793a0c9a41.png)

а именно, приведением типа labels_batch_t к тензору:
`labels_batch = torch.Tensor(list(map(int, labels_batch))).long()`

Ошибка для функции train_epoch, valid_epoch (определяются в 2 местах в ноутбуке)

Насчет поддержки Cuda:
возможна ситуация, когда установленный PyTorch скомпилен без поддержки Cuda. Проверить можно так:
```
import torch
torch.zeros(1).cuda()
```
В случае, если именно такая ситуация, об этом будет написано: `AssertionError: Torch not compiled with CUDA enabled`
Тогда решения такое:
```
pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by KaiL4eK** [comment]
Смотри, давай по каждой проблеме в-отдельности:
- В датасете надо приводить label к тензору, тогда на выходе лоадера будет пара тензоров-батчей (в описании задачи этого не было - поправил)
- Торч не компилится, а ищет CUDA сразу, поэтому переустанавливать его нет смысла
- Чем хуже проверка `torch.cuda.is_available()`?

**Comment by GeneralFire** [comment]
1. Я был не прав, да
2. Торч не компилится, но, видимо, можно случайно скачать торч без куды и тогда получить False при вызове torch.cuda.is_available(), хотя поддержка куды видяшкой есть.
3. Проверка дает ответ поддерживается ли в данных момент, но не говорит почему нет. Так, например, в моем случае видяшка имеем  поддержку, но установленный торч нет.

**Comment by KaiL4eK** [comment]
возможно была проблема с CUDA 11 - ныне установка из `pip` ставит норм версию
