### ISSUE TITLE
41_NeuralNetworks predict function undefined

### ISSUE THREAD

**Issue by GeneralFire** [KaiL4eK/ml_edu#9]
![image](https://user-images.githubusercontent.com/38854804/139958439-5d01bc3a-b728-4967-bf9f-011809b6370c.png)

Неизвестный символ predict

Решение: 
y_pred_tnsr_new = predict(model, X_tnsr) 
заменить на
y_pred_tnsr_new = model(X_tnsr)

**Comment by KaiL4eK** [comment]
Исправлено, спасибо!
